export const MSG = {
  ROOM_JOIN_REQUEST: 'ROOM_JOIN_REQUEST',
  ROOM_JOIN_ACCEPTED: 'ROOM_JOIN_ACCEPTED',
  ROOM_JOIN_REJECTED: 'ROOM_JOIN_REJECTED',
  LOBBY_STATE: 'LOBBY_STATE',
  PLAYER_READY: 'PLAYER_READY',
  GAME_START: 'GAME_START',
  ROUND_START: 'ROUND_START',
  SUBMIT_GUESS: 'SUBMIT_GUESS',
  PLAYER_GUESSED: 'PLAYER_GUESSED',
  ROUND_RESULT: 'ROUND_RESULT',
  GAME_OVER: 'GAME_OVER',
  PLAYER_LEFT: 'PLAYER_LEFT',
  TAB_SWITCH_WARNING: 'TAB_SWITCH_WARNING',
  PING: 'PING',
  PONG: 'PONG',
};

export function makeMessage(type, payload, senderId) {
  return { type, senderId, ts: Date.now(), payload };
}
